[build]
  functions = "netlify/functions"
  publish = "."
  command = "npm install"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200