[build]
  base = "weekly-meal-plan-website"
  functions = "weekly-meal-plan-website/functions"
  publish = "weekly-meal-plan-website"
  command = "npm install"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
